on: [ 'push' ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check formatting with clang-format
    steps:
    - uses: actions/checkout@v3
    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: '.'
        exclude-regex: 'crypt'
