on: [ 'push', 'pull_request' ]
  
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: x86 Ubuntu
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: gcc
          - cc: clang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: install pytest and hypothesis
        run: pip install pytest hypothesis
      - name: update ubuntu packages
        run: sudo apt-get update -y
      - name: install valgrind
        run: sudo apt-get install valgrind -y
      - name: make
        run: CC=${{matrix.cc}} make 
      - name: make check
        run: make check
  macos:
    runs-on: macos-latest
    name: MacOS (clang)
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - name: install pytest and hypothesis
        run: pip install pytest hypothesis
      - name: make
        run: make
      - name: make check
        run: make check
